print("-" * 40)
print("Menu do Terminal: \"Senta, Senta que é Banco\"")
print("-" * 40)
print()
print("Opções:")
print("[1] - Extrato Carão Crédito")
print("[2] - Extrato Cartão Débito")
print("[3] - Sacar sem Cartão")
print("[4] - Sacar")
print("[5] - Depositar")
print("[6] - Transferência")
print("[7] - Recarga Celular")
print("[0] - Sair...")
print("-" * 40)